## Housekeeping:
* Env: Latest Python + NumPy; NumPy only.
* Seeding: Set once at the top (EX: np.random.seed(42).
* Style: Vectorized NumPy only (loops penalized).
* Outputs: Use print(...); no fancy formatting; no rounding.
* Collab: Work must be your own; OK to consult official NumPy docs (no outside code).
* Errors: Show only final working code (no failed attempts).

**Explanations: After each exercise’s code block, include 1–2 lines of markdown explaining what was done.**

**Grading:** 1 point per exercise; Bonus is optional, 0 points.

**Submission:** Canvas. No naming convention.





In [525]:
import numpy as np
import random

np.random.seed(42)

### Exercise 1: Creating Arrays and Using Attributes

Create a 1D array of numbers from 1 to 10 (inclusive) using np.arange().

Create a 2D array of shape (3, 4) filled with ones using np.ones(). The default dtype is fine.

Use the shape and dtype attributes to display the shape and data type of both arrays.

In [526]:
one = np.arange(1,11)
print(one)

[ 1  2  3  4  5  6  7  8  9 10]


In [527]:
shape1 = one.shape
print(shape1)

(10,)


In [528]:
one_dtype = one.dtype
print(one_dtype)

int64


The np.arange() function is a method that creates an array of the values specified, similar to Python's range() function. It differs as it returns an array.  .shape tells you the shape of the array, and .dtype tells you the dtype.

In [529]:
array_1 = np.ones((3,4))
print(array_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [530]:
array_1s = array_1.shape
print(array_1s)

(3, 4)


In [531]:
array_1d = array_1.dtype
print(array_1d)

float64


np.ones() creates an array of all ones. Specifying np.ones([3,4]) creates the shape of the 2D array. .shape tells you the shape of the array, and .dtype tells you the dtype.

### Exercise 2: Generating Random Values and Reshaping Arrays

Create an array of 10 random integers between 0 and 50 (inclusive) using np.random.randint().

Reshape the array into a 2D array with shape (2, 5).

Find the minimum and maximum values in the array using the min() and max() methods.

In [532]:
rand_1d = np.random.randint(0,51,10)
print(rand_1d)

[38 28 14 42  7 20 38 18 22 10]


We import the random module, then create an array that contains 10 random integers between 0 and 50. In .randint(0,51,10) the 0,51 is the range to include 50, and 10 is the number of integers we want. 

In [533]:
rand_2d = rand_1d.reshape(2,5)
print(rand_2d)

[[38 28 14 42  7]
 [20 38 18 22 10]]


Here we take the first array and use .reshape() to reshape the array to be 2D, and specify the dimensions (2,5).

In [534]:
min_val = rand_2d.min()
print(min_val)

7


.min() retrieves the minimum value in the array

In [535]:
max_val = rand_2d.max()
print(max_val)

42


.max() retrieves the maximum value in the array

### Exercise 3: Indexing and Boolean Indexing

Create a 2D array from the following list of lists:

[[12, 15, 22],
 [33, 45, 52],
 [17, 28, 39]]

Extract the first row of the array as a 1D array.

Extract and print the element in the second row, third column.

Use a boolean index to extract all values greater than 30 and print as a 1D array.

In [536]:
lists = [[12, 15, 22],
         [33, 45, 52],
         [17, 28, 39]]

array_2d = np.array(lists)
print(array_2d)

[[12 15 22]
 [33 45 52]
 [17 28 39]]


np.array() converts the list into a 2D array

In [537]:
first_row_array = array_2d[0, :]
print(first_row_array)

[12 15 22]


array_2d[0, :] 0 is saying give me the first row and : is saying and all columns in that row.

In [538]:
r2_c3 = array_2d[1, 2]
print(r2_c3)


52


array_2d[x, y] retrieves the index position specified, where x is the row and y is the column.

In [539]:
bool_test = array_2d > 30
print(bool_test)

[[False False False]
 [ True  True  True]
 [False False  True]]


In [540]:
greater30 = array_2d[array_2d > 30]
print(greater30)

[33 45 52 39]


">" signifies a conditional selection where it wants everything greater than x. bool_test will show you the boolean value for each index postion whether it meets the condition. Whereas array_2d[array_2d > 30] will create an array with the values that meet the condition.

### Exercise 4: Broadcasting and Mathematical Operations

Create a 1D array with 5 random values between 0 and 10 using np.random.randint().

Create another 1D array of 5 ones.

Perform the following operations:

Addition: Add the two arrays.

Multiplication: Multiply the two arrays element-wise.

Use broadcasting to add 5 to each element of the first array.

In [541]:
r1 = np.random.randint(0,11,5)

r2 = np.ones(5)

print(r1)
print(r2)

[10  7  4  3  7]
[1. 1. 1. 1. 1.]


In [542]:
radd = r1 + r2
print(radd)

[11.  8.  5.  4.  8.]


In [543]:
rmult = r1 * r2
print(rmult)

[10.  7.  4.  3.  7.]


In [544]:
r_broadcast = r1 + 5
print(r_broadcast)

[15 12  9  8 12]


we create the first array using np.random.randint() and the second with np.ones(). We are than able to add and multiply them by simply adding/multiplying the first array to the second. Broadcasting allows us to change the values of the entire (or specified amounts) array. We are able to add 5 by simply taking the array and adding 5

### Exercise 5: Using NumPy Ufuncs

Create a 1D array of numbers from 1 to 16 (exclusive) using np.arange().

Use Numpy's sqrt() function to calculate the square root of each element in the array.

Use Numpy's sum() function to calculate the sum of all elements in the array.

Use Numpy's mean() function to calculate the mean of the array.

Note: For all operations, do not round the values.  The default dtype is fine.  Print all results.

In [545]:
array1 = np.arange(1,16)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [546]:
square = np.sqrt(array1)
print(square)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335]


In [547]:
array_sum = np.sum(array1)
print(array_sum)

120


In [548]:
array_mean = np.mean(array1)
print(array_mean)

8.0


np.arange() allows us to generate evenly spaced values without a loop. By using numpy's built in functions (.sqrt(), .sum(), .mean()) we are able to use them for mathematical operations for an array. Where np.sqrt() returns the square root for every value in the array, np.sum() returns the sum of the entire array, and np.mean returns the mean for the array. 